CREATE TABLE `browser_tabs` (
	`id` integer PRIMARY KEY NOT NULL,
	`status` text,
	`index` integer NOT NULL,
	`opener_tab_id` integer,
	`title` text,
	`url` text,
	`pending_url` text,
	`pinned` integer NOT NULL,
	`highlighted` integer NOT NULL,
	`window_id` integer NOT NULL,
	`active` integer NOT NULL,
	`fav_icon_url` text,
	`incognito` integer NOT NULL,
	`selected` integer NOT NULL,
	`audible` integer,
	`discarded` integer NOT NULL,
	`auto_discardable` integer NOT NULL,
	`width` integer,
	`height` integer,
	`session_id` text,
	`group_id` integer NOT NULL,
	`last_accessed` integer
);
