#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Navigate to the subdirectory and run lint-staged
pnpm dlx lint-staged

# Verify TypeScript files in subdirectories
# npx tsc --build self-host/tsconfig.json

