#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx commitlint --edit $1

# lint and format staged files
npx lint-staged

# verify typescript staged files
npx tsc --build self-host/tsconfig.json
npx tsc --build firebase/tsconfig.json
