name: Publish Production Docker Images

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - self-host/dev
  release:
    types: [published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-docker:
    name: Publish Production Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      IMAGE_NAME: self-hosting-maishatu
      DOCKER_REPO: pgathondu/self-hosting-maishatu

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker container
        run: |
          make build
          make push

      - name: Cleanup old Docker images
        run: |
          make cleanup
